name: Update Pacman

on:
  schedule:
    - cron: "0 */24 * * *" # Se ejecuta cada 24 horas
  workflow_dispatch: # Permite ejecutar manualmente
  push:
    branches:
      - main
      - master
      - Inicio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Descarga el repositorio
      - name: Checkout
        uses: actions/checkout@v4

      # Genera el juego de Pacman usando tus contribuciones
      - name: Pacman Gary
        uses: jasonlong/github-readme-pacman@main
        with:
          github_user_name: ${{ github.repository_owner }}
          current_branch: pacman-output
          output_directory: pacman-output
